/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProbeConteoRouteImport } from './routes/probe-conteo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedTiempoRouteImport } from './routes/_authenticated/tiempo'
import { Route as AuthenticatedTableroRouteImport } from './routes/_authenticated/tablero'
import { Route as AuthenticatedSeguridadRouteImport } from './routes/_authenticated/seguridad'
import { Route as AuthenticatedDesempenoRouteImport } from './routes/_authenticated/desempeno'
import { Route as AuthenticatedDesarrolloRouteImport } from './routes/_authenticated/desarrollo'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedComunicacionRouteImport } from './routes/_authenticated/comunicacion'
import { Route as AuthenticatedBienestarRouteImport } from './routes/_authenticated/bienestar'
import { Route as AuthenticatedAnaliticaRouteImport } from './routes/_authenticated/analitica'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores.index'
import { Route as AuthenticatedAtraccionIndexRouteImport } from './routes/_authenticated/atraccion.index'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'
import { Route as AuthenticatedAtraccionIdRouteImport } from './routes/_authenticated/atraccion.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeConteoRoute = ProbeConteoRouteImport.update({
  id: '/probe-conteo',
  path: '/probe-conteo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTiempoRoute = AuthenticatedTiempoRouteImport.update({
  id: '/tiempo',
  path: '/tiempo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableroRoute = AuthenticatedTableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeguridadRoute = AuthenticatedSeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenoRoute = AuthenticatedDesempenoRouteImport.update({
  id: '/desempeno',
  path: '/desempeno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesarrolloRoute = AuthenticatedDesarrolloRouteImport.update({
  id: '/desarrollo',
  path: '/desarrollo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacionRoute =
  AuthenticatedComunicacionRouteImport.update({
    id: '/comunicacion',
    path: '/comunicacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBienestarRoute = AuthenticatedBienestarRouteImport.update({
  id: '/bienestar',
  path: '/bienestar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliticaRoute = AuthenticatedAnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtraccionIndexRoute =
  AuthenticatedAtraccionIndexRouteImport.update({
    id: '/atraccion/',
    path: '/atraccion/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/colaboradores/$id',
    path: '/colaboradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtraccionIdRoute =
  AuthenticatedAtraccionIdRouteImport.update({
    id: '/atraccion/$id',
    path: '/atraccion/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/probe-conteo': typeof ProbeConteoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analitica': typeof AuthenticatedAnaliticaRoute
  '/bienestar': typeof AuthenticatedBienestarRoute
  '/comunicacion': typeof AuthenticatedComunicacionRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/desarrollo': typeof AuthenticatedDesarrolloRoute
  '/desempeno': typeof AuthenticatedDesempenoRoute
  '/seguridad': typeof AuthenticatedSeguridadRoute
  '/tablero': typeof AuthenticatedTableroRoute
  '/tiempo': typeof AuthenticatedTiempoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atraccion/$id': typeof AuthenticatedAtraccionIdRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/atraccion/': typeof AuthenticatedAtraccionIndexRoute
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/probe-conteo': typeof ProbeConteoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analitica': typeof AuthenticatedAnaliticaRoute
  '/bienestar': typeof AuthenticatedBienestarRoute
  '/comunicacion': typeof AuthenticatedComunicacionRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/desarrollo': typeof AuthenticatedDesarrolloRoute
  '/desempeno': typeof AuthenticatedDesempenoRoute
  '/seguridad': typeof AuthenticatedSeguridadRoute
  '/tablero': typeof AuthenticatedTableroRoute
  '/tiempo': typeof AuthenticatedTiempoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/atraccion/$id': typeof AuthenticatedAtraccionIdRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/atraccion': typeof AuthenticatedAtraccionIndexRoute
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/probe-conteo': typeof ProbeConteoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analitica': typeof AuthenticatedAnaliticaRoute
  '/_authenticated/bienestar': typeof AuthenticatedBienestarRoute
  '/_authenticated/comunicacion': typeof AuthenticatedComunicacionRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/desarrollo': typeof AuthenticatedDesarrolloRoute
  '/_authenticated/desempeno': typeof AuthenticatedDesempenoRoute
  '/_authenticated/seguridad': typeof AuthenticatedSeguridadRoute
  '/_authenticated/tablero': typeof AuthenticatedTableroRoute
  '/_authenticated/tiempo': typeof AuthenticatedTiempoRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/_authenticated/atraccion/$id': typeof AuthenticatedAtraccionIdRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/atraccion/': typeof AuthenticatedAtraccionIndexRoute
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/probe-conteo'
    | '/sitemap.xml'
    | '/analitica'
    | '/bienestar'
    | '/comunicacion'
    | '/configuracion'
    | '/desarrollo'
    | '/desempeno'
    | '/seguridad'
    | '/tablero'
    | '/tiempo'
    | '/auth/callback'
    | '/atraccion/$id'
    | '/colaboradores/$id'
    | '/atraccion/'
    | '/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/probe-conteo'
    | '/sitemap.xml'
    | '/analitica'
    | '/bienestar'
    | '/comunicacion'
    | '/configuracion'
    | '/desarrollo'
    | '/desempeno'
    | '/seguridad'
    | '/tablero'
    | '/tiempo'
    | '/auth/callback'
    | '/atraccion/$id'
    | '/colaboradores/$id'
    | '/atraccion'
    | '/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/probe-conteo'
    | '/sitemap.xml'
    | '/_authenticated/analitica'
    | '/_authenticated/bienestar'
    | '/_authenticated/comunicacion'
    | '/_authenticated/configuracion'
    | '/_authenticated/desarrollo'
    | '/_authenticated/desempeno'
    | '/_authenticated/seguridad'
    | '/_authenticated/tablero'
    | '/_authenticated/tiempo'
    | '/auth_/callback'
    | '/_authenticated/atraccion/$id'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/atraccion/'
    | '/_authenticated/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProbeConteoRoute: typeof ProbeConteoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe-conteo': {
      id: '/probe-conteo'
      path: '/probe-conteo'
      fullPath: '/probe-conteo'
      preLoaderRoute: typeof ProbeConteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tiempo': {
      id: '/_authenticated/tiempo'
      path: '/tiempo'
      fullPath: '/tiempo'
      preLoaderRoute: typeof AuthenticatedTiempoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tablero': {
      id: '/_authenticated/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof AuthenticatedTableroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguridad': {
      id: '/_authenticated/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof AuthenticatedSeguridadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempeno': {
      id: '/_authenticated/desempeno'
      path: '/desempeno'
      fullPath: '/desempeno'
      preLoaderRoute: typeof AuthenticatedDesempenoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desarrollo': {
      id: '/_authenticated/desarrollo'
      path: '/desarrollo'
      fullPath: '/desarrollo'
      preLoaderRoute: typeof AuthenticatedDesarrolloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacion': {
      id: '/_authenticated/comunicacion'
      path: '/comunicacion'
      fullPath: '/comunicacion'
      preLoaderRoute: typeof AuthenticatedComunicacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bienestar': {
      id: '/_authenticated/bienestar'
      path: '/bienestar'
      fullPath: '/bienestar'
      preLoaderRoute: typeof AuthenticatedBienestarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analitica': {
      id: '/_authenticated/analitica'
      path: '/analitica'
      fullPath: '/analitica'
      preLoaderRoute: typeof AuthenticatedAnaliticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atraccion/': {
      id: '/_authenticated/atraccion/'
      path: '/atraccion'
      fullPath: '/atraccion/'
      preLoaderRoute: typeof AuthenticatedAtraccionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atraccion/$id': {
      id: '/_authenticated/atraccion/$id'
      path: '/atraccion/$id'
      fullPath: '/atraccion/$id'
      preLoaderRoute: typeof AuthenticatedAtraccionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnaliticaRoute: typeof AuthenticatedAnaliticaRoute
  AuthenticatedBienestarRoute: typeof AuthenticatedBienestarRoute
  AuthenticatedComunicacionRoute: typeof AuthenticatedComunicacionRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDesarrolloRoute: typeof AuthenticatedDesarrolloRoute
  AuthenticatedDesempenoRoute: typeof AuthenticatedDesempenoRoute
  AuthenticatedSeguridadRoute: typeof AuthenticatedSeguridadRoute
  AuthenticatedTableroRoute: typeof AuthenticatedTableroRoute
  AuthenticatedTiempoRoute: typeof AuthenticatedTiempoRoute
  AuthenticatedAtraccionIdRoute: typeof AuthenticatedAtraccionIdRoute
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
  AuthenticatedAtraccionIndexRoute: typeof AuthenticatedAtraccionIndexRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnaliticaRoute: AuthenticatedAnaliticaRoute,
  AuthenticatedBienestarRoute: AuthenticatedBienestarRoute,
  AuthenticatedComunicacionRoute: AuthenticatedComunicacionRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDesarrolloRoute: AuthenticatedDesarrolloRoute,
  AuthenticatedDesempenoRoute: AuthenticatedDesempenoRoute,
  AuthenticatedSeguridadRoute: AuthenticatedSeguridadRoute,
  AuthenticatedTableroRoute: AuthenticatedTableroRoute,
  AuthenticatedTiempoRoute: AuthenticatedTiempoRoute,
  AuthenticatedAtraccionIdRoute: AuthenticatedAtraccionIdRoute,
  AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  AuthenticatedAtraccionIndexRoute: AuthenticatedAtraccionIndexRoute,
  AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProbeConteoRoute: ProbeConteoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
